name: contact_me
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http_parser: 3.1.4
  mime: 0.9.7
  http: 0.12.2
  logger: 0.9.4
  flutter_svprogresshud: 0.0.6
  loading: 1.0.2
  # let_log: 1.1.4
  path: ^1.8.0-nullsafety.1
  dio: 3.0.10
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety
  equatable: 1.2.5
  get_test: 3.13.3
  cupertino_icons: ^0.1.3
  flutter_form_builder: ^3.14.1
  get: ^3.21.1
  getwidget: ^1.2.2
  google_fonts: ^1.1.1
  velocity_x: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3

flutter:
  uses-material-design: true